server:
  port: 8081

spring:
  app:
    jwtSecret: ni24g6hk5ba5a65a6x6s2c6c6s2
    jwtExpirationMs: 36000000

  datasource:
    url: jdbc:postgresql://localhost:5432/AcademicEmploymentSystem
    username: postgres
    password: Kyuubi279
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl_auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format-sql: true
        database: postgres
        database-platform: org.hibernate.dialect.PostgreSQLDialect

